default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  host:  <%= ENV["MYSQL_HOST"] %>
  username: root
  password: <%= ENV["MYSQL_ROOT_PASSWORD"] %>
  database: project_rails

test:
  <<: *default
  host:  <%= ENV["MYSQL_HOST"] %>
  username: root
  password: <%= ENV["MYSQL_ROOT_PASSWORD"] %>
  database: project_railstest<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
  host:  <%= ENV["MYSQL_HOST"] %>
  username: root
  password: <%= ENV["MYSQL_ROOT_PASSWORD"] %>
  database: <%= ENV["MYSQL_DATABASE"] %>
