default: &default
  adapter: mysql2_json
  pool: 5
  encoding: utf8
  timeout: 5000

development:
  <<: *default
  host:  <%= ENV["MYSQL_HOST"] %>
  username: root
  password: <%= ENV["MYSQL_ROOT_PASSWORD"] %>
  database: project_rails

test:
  <<: *default
  host:  <%= ENV["MYSQL_HOST"] %>
  username: root
  password: <%= ENV["MYSQL_ROOT_PASSWORD"] %>
  database: project_railstest<%= ENV['TEST_ENV_NUMBER'] %>

production:
  adapter: mysql2
  reconnect: false
  database: <%= ENV["GH_CLIENT_DBNAME"] %>
  username: <%= ENV["GH_CLIENT_USERNAME"] %>
  password: <%= ENV["GH_CLIENT_PASS"] %>
  host: <%= ENV["GH_CLIENT_HOST"] %>
