default: &default
  adapter: mysql2
  pool: 5
  encoding: utf8
  timeout: 5000

development:
  <<: *default
  host: 172.17.0.2
  username: root
  password: 1234
  database: project_rails

test:
  <<: *default
  host: 172.17.0.2
  username: root
  password: 1234
  database: project_railstest<%= ENV['TEST_ENV_NUMBER'] %>

production:
  adapter: mysql2
  reconnect: false
  database: <%= ENV["GH_CLIENT_DBNAME"] %>
  username: <%= ENV["GH_CLIENT_USERNAME"] %>
  password: <%= ENV["GH_CLIENT_PASS"] %>
  host: <%= ENV["GH_CLIENT_HOST"] %>
